// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_header.proto

package com.wenweihu86.rpc.codec;

public final class RPCHeader {
  private RPCHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code codec.CompressType}
   */
  public enum CompressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COMPRESS_NO = 0;</code>
     */
    COMPRESS_NO(0),
    /**
     * <code>COMPRESS_SNAPPY = 1;</code>
     */
    COMPRESS_SNAPPY(1),
    /**
     * <code>COMPERESS_GZIP = 2;</code>
     */
    COMPERESS_GZIP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>COMPRESS_NO = 0;</code>
     */
    public static final int COMPRESS_NO_VALUE = 0;
    /**
     * <code>COMPRESS_SNAPPY = 1;</code>
     */
    public static final int COMPRESS_SNAPPY_VALUE = 1;
    /**
     * <code>COMPERESS_GZIP = 2;</code>
     */
    public static final int COMPERESS_GZIP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CompressType valueOf(int value) {
      return forNumber(value);
    }

    public static CompressType forNumber(int value) {
      switch (value) {
        case 0: return COMPRESS_NO;
        case 1: return COMPRESS_SNAPPY;
        case 2: return COMPERESS_GZIP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CompressType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressType>() {
            public CompressType findValueByNumber(int number) {
              return CompressType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.RPCHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final CompressType[] VALUES = values();

    public static CompressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CompressType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:codec.CompressType)
  }

  /**
   * Protobuf enum {@code codec.ResCode}
   */
  public enum ResCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RES_SUCCESS = 0;</code>
     */
    RES_SUCCESS(0),
    /**
     * <code>RES_FAIL = 1;</code>
     */
    RES_FAIL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RES_SUCCESS = 0;</code>
     */
    public static final int RES_SUCCESS_VALUE = 0;
    /**
     * <code>RES_FAIL = 1;</code>
     */
    public static final int RES_FAIL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResCode forNumber(int value) {
      switch (value) {
        case 0: return RES_SUCCESS;
        case 1: return RES_FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResCode>() {
            public ResCode findValueByNumber(int number) {
              return ResCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.RPCHeader.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResCode[] VALUES = values();

    public static ResCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:codec.ResCode)
  }

  public interface RequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codec.RequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serviceName = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>optional string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>optional string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional string logId = 3;</code>
     */
    java.lang.String getLogId();
    /**
     * <code>optional string logId = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>optional .codec.CompressType compressType = 4;</code>
     */
    int getCompressTypeValue();
    /**
     * <code>optional .codec.CompressType compressType = 4;</code>
     */
    com.wenweihu86.rpc.codec.RPCHeader.CompressType getCompressType();

    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */
    int getCustomParamCount();
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */
    boolean containsCustomParam(
        java.lang.String key);
    /**
     * Use {@link #getCustomParamMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getCustomParam();
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getCustomParamMap();
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    java.lang.String getCustomParamOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    java.lang.String getCustomParamOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code codec.RequestHeader}
   */
  public  static final class RequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:codec.RequestHeader)
      RequestHeaderOrBuilder {
    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestHeader() {
      serviceName_ = "";
      methodName_ = "";
      logId_ = "";
      compressType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              compressType_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                customParam_ = com.google.protobuf.MapField.newMapField(
                    CustomParamDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              customParam__ = input.readMessage(
                  CustomParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              customParam_.getMutableMap().put(
                  customParam__.getKey(), customParam__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetCustomParam();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.class, com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.Builder.class);
    }

    private int bitField0_;
    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>optional string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGID_FIELD_NUMBER = 3;
    private volatile java.lang.Object logId_;
    /**
     * <code>optional string logId = 3;</code>
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPRESSTYPE_FIELD_NUMBER = 4;
    private int compressType_;
    /**
     * <code>optional .codec.CompressType compressType = 4;</code>
     */
    public int getCompressTypeValue() {
      return compressType_;
    }
    /**
     * <code>optional .codec.CompressType compressType = 4;</code>
     */
    public com.wenweihu86.rpc.codec.RPCHeader.CompressType getCompressType() {
      com.wenweihu86.rpc.codec.RPCHeader.CompressType result = com.wenweihu86.rpc.codec.RPCHeader.CompressType.valueOf(compressType_);
      return result == null ? com.wenweihu86.rpc.codec.RPCHeader.CompressType.UNRECOGNIZED : result;
    }

    public static final int CUSTOMPARAM_FIELD_NUMBER = 5;
    private static final class CustomParamDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_CustomParamEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> customParam_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetCustomParam() {
      if (customParam_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomParamDefaultEntryHolder.defaultEntry);
      }
      return customParam_;
    }

    public int getCustomParamCount() {
      return internalGetCustomParam().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    public boolean containsCustomParam(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCustomParam().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomParamMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getCustomParam() {
      return getCustomParamMap();
    }
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getCustomParamMap() {
      return internalGetCustomParam().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    public java.lang.String getCustomParamOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomParam().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; customParam = 5;</code>
     */

    public java.lang.String getCustomParamOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomParam().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (!getLogIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, logId_);
      }
      if (compressType_ != com.wenweihu86.rpc.codec.RPCHeader.CompressType.COMPRESS_NO.getNumber()) {
        output.writeEnum(4, compressType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCustomParam(),
          CustomParamDefaultEntryHolder.defaultEntry,
          5);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (!getLogIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, logId_);
      }
      if (compressType_ != com.wenweihu86.rpc.codec.RPCHeader.CompressType.COMPRESS_NO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, compressType_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetCustomParam().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        customParam__ = CustomParamDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, customParam__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wenweihu86.rpc.codec.RPCHeader.RequestHeader)) {
        return super.equals(obj);
      }
      com.wenweihu86.rpc.codec.RPCHeader.RequestHeader other = (com.wenweihu86.rpc.codec.RPCHeader.RequestHeader) obj;

      boolean result = true;
      result = result && getServiceName()
          .equals(other.getServiceName());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && getLogId()
          .equals(other.getLogId());
      result = result && compressType_ == other.compressType_;
      result = result && internalGetCustomParam().equals(
          other.internalGetCustomParam());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + LOGID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      hash = (37 * hash) + COMPRESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + compressType_;
      if (!internalGetCustomParam().getMap().isEmpty()) {
        hash = (37 * hash) + CUSTOMPARAM_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCustomParam().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wenweihu86.rpc.codec.RPCHeader.RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code codec.RequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codec.RequestHeader)
        com.wenweihu86.rpc.codec.RPCHeader.RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetCustomParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableCustomParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.class, com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.Builder.class);
      }

      // Construct using com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceName_ = "";

        methodName_ = "";

        logId_ = "";

        compressType_ = 0;

        internalGetMutableCustomParam().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_RequestHeader_descriptor;
      }

      public com.wenweihu86.rpc.codec.RPCHeader.RequestHeader getDefaultInstanceForType() {
        return com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.getDefaultInstance();
      }

      public com.wenweihu86.rpc.codec.RPCHeader.RequestHeader build() {
        com.wenweihu86.rpc.codec.RPCHeader.RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wenweihu86.rpc.codec.RPCHeader.RequestHeader buildPartial() {
        com.wenweihu86.rpc.codec.RPCHeader.RequestHeader result = new com.wenweihu86.rpc.codec.RPCHeader.RequestHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.serviceName_ = serviceName_;
        result.methodName_ = methodName_;
        result.logId_ = logId_;
        result.compressType_ = compressType_;
        result.customParam_ = internalGetCustomParam();
        result.customParam_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wenweihu86.rpc.codec.RPCHeader.RequestHeader) {
          return mergeFrom((com.wenweihu86.rpc.codec.RPCHeader.RequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wenweihu86.rpc.codec.RPCHeader.RequestHeader other) {
        if (other == com.wenweihu86.rpc.codec.RPCHeader.RequestHeader.getDefaultInstance()) return this;
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        if (other.compressType_ != 0) {
          setCompressTypeValue(other.getCompressTypeValue());
        }
        internalGetMutableCustomParam().mergeFrom(
            other.internalGetCustomParam());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wenweihu86.rpc.codec.RPCHeader.RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wenweihu86.rpc.codec.RPCHeader.RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder clearServiceName() {
        
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>optional string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logId_ = "";
      /**
       * <code>optional string logId = 3;</code>
       */
      public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        java.lang.Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder setLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private int compressType_ = 0;
      /**
       * <code>optional .codec.CompressType compressType = 4;</code>
       */
      public int getCompressTypeValue() {
        return compressType_;
      }
      /**
       * <code>optional .codec.CompressType compressType = 4;</code>
       */
      public Builder setCompressTypeValue(int value) {
        compressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .codec.CompressType compressType = 4;</code>
       */
      public com.wenweihu86.rpc.codec.RPCHeader.CompressType getCompressType() {
        com.wenweihu86.rpc.codec.RPCHeader.CompressType result = com.wenweihu86.rpc.codec.RPCHeader.CompressType.valueOf(compressType_);
        return result == null ? com.wenweihu86.rpc.codec.RPCHeader.CompressType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .codec.CompressType compressType = 4;</code>
       */
      public Builder setCompressType(com.wenweihu86.rpc.codec.RPCHeader.CompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        compressType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .codec.CompressType compressType = 4;</code>
       */
      public Builder clearCompressType() {
        
        compressType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> customParam_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetCustomParam() {
        if (customParam_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CustomParamDefaultEntryHolder.defaultEntry);
        }
        return customParam_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableCustomParam() {
        onChanged();;
        if (customParam_ == null) {
          customParam_ = com.google.protobuf.MapField.newMapField(
              CustomParamDefaultEntryHolder.defaultEntry);
        }
        if (!customParam_.isMutable()) {
          customParam_ = customParam_.copy();
        }
        return customParam_;
      }

      public int getCustomParamCount() {
        return internalGetCustomParam().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public boolean containsCustomParam(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetCustomParam().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCustomParamMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getCustomParam() {
        return getCustomParamMap();
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getCustomParamMap() {
        return internalGetCustomParam().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public java.lang.String getCustomParamOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetCustomParam().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public java.lang.String getCustomParamOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetCustomParam().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCustomParam() {
        getMutableCustomParam().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public Builder removeCustomParam(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableCustomParam().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableCustomParam() {
        return internalGetMutableCustomParam().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */
      public Builder putCustomParam(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableCustomParam().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; customParam = 5;</code>
       */

      public Builder putAllCustomParam(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableCustomParam().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:codec.RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:codec.RequestHeader)
    private static final com.wenweihu86.rpc.codec.RPCHeader.RequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wenweihu86.rpc.codec.RPCHeader.RequestHeader();
    }

    public static com.wenweihu86.rpc.codec.RPCHeader.RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      public RequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    public com.wenweihu86.rpc.codec.RPCHeader.RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codec.ResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string logId = 1;</code>
     */
    java.lang.String getLogId();
    /**
     * <code>optional string logId = 1;</code>
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>optional .codec.ResCode resCode = 2;</code>
     */
    int getResCodeValue();
    /**
     * <code>optional .codec.ResCode resCode = 2;</code>
     */
    com.wenweihu86.rpc.codec.RPCHeader.ResCode getResCode();

    /**
     * <code>optional string resMsg = 3;</code>
     */
    java.lang.String getResMsg();
    /**
     * <code>optional string resMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getResMsgBytes();
  }
  /**
   * Protobuf type {@code codec.ResponseHeader}
   */
  public  static final class ResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:codec.ResponseHeader)
      ResponseHeaderOrBuilder {
    // Use ResponseHeader.newBuilder() to construct.
    private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseHeader() {
      logId_ = "";
      resCode_ = 0;
      resMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              resCode_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              resMsg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_ResponseHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_ResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.class, com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.Builder.class);
    }

    public static final int LOGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object logId_;
    /**
     * <code>optional string logId = 1;</code>
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESCODE_FIELD_NUMBER = 2;
    private int resCode_;
    /**
     * <code>optional .codec.ResCode resCode = 2;</code>
     */
    public int getResCodeValue() {
      return resCode_;
    }
    /**
     * <code>optional .codec.ResCode resCode = 2;</code>
     */
    public com.wenweihu86.rpc.codec.RPCHeader.ResCode getResCode() {
      com.wenweihu86.rpc.codec.RPCHeader.ResCode result = com.wenweihu86.rpc.codec.RPCHeader.ResCode.valueOf(resCode_);
      return result == null ? com.wenweihu86.rpc.codec.RPCHeader.ResCode.UNRECOGNIZED : result;
    }

    public static final int RESMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object resMsg_;
    /**
     * <code>optional string resMsg = 3;</code>
     */
    public java.lang.String getResMsg() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLogIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logId_);
      }
      if (resCode_ != com.wenweihu86.rpc.codec.RPCHeader.ResCode.RES_SUCCESS.getNumber()) {
        output.writeEnum(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resMsg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLogIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logId_);
      }
      if (resCode_ != com.wenweihu86.rpc.codec.RPCHeader.ResCode.RES_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resMsg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader)) {
        return super.equals(obj);
      }
      com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader other = (com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader) obj;

      boolean result = true;
      result = result && getLogId()
          .equals(other.getLogId());
      result = result && resCode_ == other.resCode_;
      result = result && getResMsg()
          .equals(other.getResMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LOGID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      hash = (37 * hash) + RESCODE_FIELD_NUMBER;
      hash = (53 * hash) + resCode_;
      hash = (37 * hash) + RESMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code codec.ResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codec.ResponseHeader)
        com.wenweihu86.rpc.codec.RPCHeader.ResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_ResponseHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.class, com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.Builder.class);
      }

      // Construct using com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        logId_ = "";

        resCode_ = 0;

        resMsg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wenweihu86.rpc.codec.RPCHeader.internal_static_codec_ResponseHeader_descriptor;
      }

      public com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader getDefaultInstanceForType() {
        return com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.getDefaultInstance();
      }

      public com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader build() {
        com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader buildPartial() {
        com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader result = new com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader(this);
        result.logId_ = logId_;
        result.resCode_ = resCode_;
        result.resMsg_ = resMsg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader) {
          return mergeFrom((com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader other) {
        if (other == com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader.getDefaultInstance()) return this;
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        if (other.resCode_ != 0) {
          setResCodeValue(other.getResCodeValue());
        }
        if (!other.getResMsg().isEmpty()) {
          resMsg_ = other.resMsg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object logId_ = "";
      /**
       * <code>optional string logId = 1;</code>
       */
      public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        java.lang.Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder setLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private int resCode_ = 0;
      /**
       * <code>optional .codec.ResCode resCode = 2;</code>
       */
      public int getResCodeValue() {
        return resCode_;
      }
      /**
       * <code>optional .codec.ResCode resCode = 2;</code>
       */
      public Builder setResCodeValue(int value) {
        resCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .codec.ResCode resCode = 2;</code>
       */
      public com.wenweihu86.rpc.codec.RPCHeader.ResCode getResCode() {
        com.wenweihu86.rpc.codec.RPCHeader.ResCode result = com.wenweihu86.rpc.codec.RPCHeader.ResCode.valueOf(resCode_);
        return result == null ? com.wenweihu86.rpc.codec.RPCHeader.ResCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .codec.ResCode resCode = 2;</code>
       */
      public Builder setResCode(com.wenweihu86.rpc.codec.RPCHeader.ResCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .codec.ResCode resCode = 2;</code>
       */
      public Builder clearResCode() {
        
        resCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resMsg_ = "";
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public java.lang.String getResMsg() {
        java.lang.Object ref = resMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        java.lang.Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder setResMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder clearResMsg() {
        
        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:codec.ResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:codec.ResponseHeader)
    private static final com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader();
    }

    public static com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
      public ResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
      return PARSER;
    }

    public com.wenweihu86.rpc.codec.RPCHeader.ResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_RequestHeader_CustomParamEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_RequestHeader_CustomParamEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_ResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rpc_header.proto\022\005codec\"\342\001\n\rRequestHea" +
      "der\022\023\n\013serviceName\030\001 \001(\t\022\022\n\nmethodName\030\002" +
      " \001(\t\022\r\n\005logId\030\003 \001(\t\022)\n\014compressType\030\004 \001(" +
      "\0162\023.codec.CompressType\022:\n\013customParam\030\005 " +
      "\003(\0132%.codec.RequestHeader.CustomParamEnt" +
      "ry\0322\n\020CustomParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"P\n\016ResponseHeader\022\r\n\005logI" +
      "d\030\001 \001(\t\022\037\n\007resCode\030\002 \001(\0162\016.codec.ResCode" +
      "\022\016\n\006resMsg\030\003 \001(\t*H\n\014CompressType\022\017\n\013COMP" +
      "RESS_NO\020\000\022\023\n\017COMPRESS_SNAPPY\020\001\022\022\n\016COMPER",
      "ESS_GZIP\020\002*(\n\007ResCode\022\017\n\013RES_SUCCESS\020\000\022\014" +
      "\n\010RES_FAIL\020\001B%\n\030com.wenweihu86.rpc.codec" +
      "B\tRPCHeaderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_codec_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codec_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_RequestHeader_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "LogId", "CompressType", "CustomParam", });
    internal_static_codec_RequestHeader_CustomParamEntry_descriptor =
      internal_static_codec_RequestHeader_descriptor.getNestedTypes().get(0);
    internal_static_codec_RequestHeader_CustomParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_RequestHeader_CustomParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_codec_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_codec_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_ResponseHeader_descriptor,
        new java.lang.String[] { "LogId", "ResCode", "ResMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
