// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protov3_header.proto

package com.wenweihu86.rpc.codec.proto3;

public final class ProtoV3Header {
  private ProtoV3Header() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto3.CompressType}
   */
  public enum CompressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COMPRESS_NO = 0;</code>
     */
    COMPRESS_NO(0),
    /**
     * <code>COMPRESS_SNAPPY = 1;</code>
     */
    COMPRESS_SNAPPY(1),
    /**
     * <code>COMPERESS_GZIP = 2;</code>
     */
    COMPERESS_GZIP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>COMPRESS_NO = 0;</code>
     */
    public static final int COMPRESS_NO_VALUE = 0;
    /**
     * <code>COMPRESS_SNAPPY = 1;</code>
     */
    public static final int COMPRESS_SNAPPY_VALUE = 1;
    /**
     * <code>COMPERESS_GZIP = 2;</code>
     */
    public static final int COMPERESS_GZIP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CompressType valueOf(int value) {
      return forNumber(value);
    }

    public static CompressType forNumber(int value) {
      switch (value) {
        case 0: return COMPRESS_NO;
        case 1: return COMPRESS_SNAPPY;
        case 2: return COMPERESS_GZIP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CompressType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressType>() {
            public CompressType findValueByNumber(int number) {
              return CompressType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.getDescriptor().getEnumTypes().get(0);
    }

    private static final CompressType[] VALUES = values();

    public static CompressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CompressType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto3.CompressType)
  }

  public interface RequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto3.RequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serviceName = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>optional string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>optional string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional string logId = 3;</code>
     */
    java.lang.String getLogId();
    /**
     * <code>optional string logId = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>optional .proto3.CompressType compressType = 4;</code>
     */
    int getCompressTypeValue();
    /**
     * <code>optional .proto3.CompressType compressType = 4;</code>
     */
    com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType getCompressType();

    /**
     * <code>optional string customParam = 5;</code>
     */
    java.lang.String getCustomParam();
    /**
     * <code>optional string customParam = 5;</code>
     */
    com.google.protobuf.ByteString
        getCustomParamBytes();
  }
  /**
   * Protobuf type {@code proto3.RequestHeader}
   */
  public  static final class RequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto3.RequestHeader)
      RequestHeaderOrBuilder {
    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestHeader() {
      serviceName_ = "";
      methodName_ = "";
      logId_ = "";
      compressType_ = 0;
      customParam_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              compressType_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              customParam_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_RequestHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.class, com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.Builder.class);
    }

    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>optional string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGID_FIELD_NUMBER = 3;
    private volatile java.lang.Object logId_;
    /**
     * <code>optional string logId = 3;</code>
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPRESSTYPE_FIELD_NUMBER = 4;
    private int compressType_;
    /**
     * <code>optional .proto3.CompressType compressType = 4;</code>
     */
    public int getCompressTypeValue() {
      return compressType_;
    }
    /**
     * <code>optional .proto3.CompressType compressType = 4;</code>
     */
    public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType getCompressType() {
      com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType result = com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.valueOf(compressType_);
      return result == null ? com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.UNRECOGNIZED : result;
    }

    public static final int CUSTOMPARAM_FIELD_NUMBER = 5;
    private volatile java.lang.Object customParam_;
    /**
     * <code>optional string customParam = 5;</code>
     */
    public java.lang.String getCustomParam() {
      java.lang.Object ref = customParam_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customParam_ = s;
        return s;
      }
    }
    /**
     * <code>optional string customParam = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCustomParamBytes() {
      java.lang.Object ref = customParam_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (!getLogIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, logId_);
      }
      if (compressType_ != com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.COMPRESS_NO.getNumber()) {
        output.writeEnum(4, compressType_);
      }
      if (!getCustomParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customParam_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (!getLogIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, logId_);
      }
      if (compressType_ != com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.COMPRESS_NO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, compressType_);
      }
      if (!getCustomParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customParam_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader)) {
        return super.equals(obj);
      }
      com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader other = (com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader) obj;

      boolean result = true;
      result = result && getServiceName()
          .equals(other.getServiceName());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && getLogId()
          .equals(other.getLogId());
      result = result && compressType_ == other.compressType_;
      result = result && getCustomParam()
          .equals(other.getCustomParam());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + LOGID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      hash = (37 * hash) + COMPRESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + compressType_;
      hash = (37 * hash) + CUSTOMPARAM_FIELD_NUMBER;
      hash = (53 * hash) + getCustomParam().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto3.RequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto3.RequestHeader)
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_RequestHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.class, com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.Builder.class);
      }

      // Construct using com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceName_ = "";

        methodName_ = "";

        logId_ = "";

        compressType_ = 0;

        customParam_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_RequestHeader_descriptor;
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader getDefaultInstanceForType() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.getDefaultInstance();
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader build() {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader buildPartial() {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader result = new com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader(this);
        result.serviceName_ = serviceName_;
        result.methodName_ = methodName_;
        result.logId_ = logId_;
        result.compressType_ = compressType_;
        result.customParam_ = customParam_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader) {
          return mergeFrom((com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader other) {
        if (other == com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader.getDefaultInstance()) return this;
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        if (other.compressType_ != 0) {
          setCompressTypeValue(other.getCompressTypeValue());
        }
        if (!other.getCustomParam().isEmpty()) {
          customParam_ = other.customParam_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder clearServiceName() {
        
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>optional string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logId_ = "";
      /**
       * <code>optional string logId = 3;</code>
       */
      public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        java.lang.Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder setLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 3;</code>
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private int compressType_ = 0;
      /**
       * <code>optional .proto3.CompressType compressType = 4;</code>
       */
      public int getCompressTypeValue() {
        return compressType_;
      }
      /**
       * <code>optional .proto3.CompressType compressType = 4;</code>
       */
      public Builder setCompressTypeValue(int value) {
        compressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto3.CompressType compressType = 4;</code>
       */
      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType getCompressType() {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType result = com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.valueOf(compressType_);
        return result == null ? com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto3.CompressType compressType = 4;</code>
       */
      public Builder setCompressType(com.wenweihu86.rpc.codec.proto3.ProtoV3Header.CompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        compressType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto3.CompressType compressType = 4;</code>
       */
      public Builder clearCompressType() {
        
        compressType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object customParam_ = "";
      /**
       * <code>optional string customParam = 5;</code>
       */
      public java.lang.String getCustomParam() {
        java.lang.Object ref = customParam_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customParam_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customParam = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCustomParamBytes() {
        java.lang.Object ref = customParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customParam = 5;</code>
       */
      public Builder setCustomParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customParam = 5;</code>
       */
      public Builder clearCustomParam() {
        
        customParam_ = getDefaultInstance().getCustomParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customParam = 5;</code>
       */
      public Builder setCustomParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customParam_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto3.RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:proto3.RequestHeader)
    private static final com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader();
    }

    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      public RequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto3.ResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string logId = 1;</code>
     */
    java.lang.String getLogId();
    /**
     * <code>optional string logId = 1;</code>
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>optional int32 resCode = 2;</code>
     */
    int getResCode();

    /**
     * <code>optional string resMsg = 3;</code>
     */
    java.lang.String getResMsg();
    /**
     * <code>optional string resMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getResMsgBytes();
  }
  /**
   * Protobuf type {@code proto3.ResponseHeader}
   */
  public  static final class ResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto3.ResponseHeader)
      ResponseHeaderOrBuilder {
    // Use ResponseHeader.newBuilder() to construct.
    private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseHeader() {
      logId_ = "";
      resCode_ = 0;
      resMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 16: {

              resCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              resMsg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_ResponseHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_ResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.class, com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.Builder.class);
    }

    public static final int LOGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object logId_;
    /**
     * <code>optional string logId = 1;</code>
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESCODE_FIELD_NUMBER = 2;
    private int resCode_;
    /**
     * <code>optional int32 resCode = 2;</code>
     */
    public int getResCode() {
      return resCode_;
    }

    public static final int RESMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object resMsg_;
    /**
     * <code>optional string resMsg = 3;</code>
     */
    public java.lang.String getResMsg() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLogIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logId_);
      }
      if (resCode_ != 0) {
        output.writeInt32(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resMsg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLogIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logId_);
      }
      if (resCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resMsg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader)) {
        return super.equals(obj);
      }
      com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader other = (com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader) obj;

      boolean result = true;
      result = result && getLogId()
          .equals(other.getLogId());
      result = result && (getResCode()
          == other.getResCode());
      result = result && getResMsg()
          .equals(other.getResMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LOGID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      hash = (37 * hash) + RESCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResCode();
      hash = (37 * hash) + RESMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto3.ResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto3.ResponseHeader)
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_ResponseHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.class, com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.Builder.class);
      }

      // Construct using com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        logId_ = "";

        resCode_ = 0;

        resMsg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.internal_static_proto3_ResponseHeader_descriptor;
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader getDefaultInstanceForType() {
        return com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.getDefaultInstance();
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader build() {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader buildPartial() {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader result = new com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader(this);
        result.logId_ = logId_;
        result.resCode_ = resCode_;
        result.resMsg_ = resMsg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader) {
          return mergeFrom((com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader other) {
        if (other == com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader.getDefaultInstance()) return this;
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        if (other.getResCode() != 0) {
          setResCode(other.getResCode());
        }
        if (!other.getResMsg().isEmpty()) {
          resMsg_ = other.resMsg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object logId_ = "";
      /**
       * <code>optional string logId = 1;</code>
       */
      public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        java.lang.Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder setLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logId = 1;</code>
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private int resCode_ ;
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public int getResCode() {
        return resCode_;
      }
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public Builder setResCode(int value) {
        
        resCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resCode = 2;</code>
       */
      public Builder clearResCode() {
        
        resCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resMsg_ = "";
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public java.lang.String getResMsg() {
        java.lang.Object ref = resMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        java.lang.Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder setResMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder clearResMsg() {
        
        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 3;</code>
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto3.ResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:proto3.ResponseHeader)
    private static final com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader();
    }

    public static com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
      public ResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
      return PARSER;
    }

    public com.wenweihu86.rpc.codec.proto3.ProtoV3Header.ResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto3_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto3_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto3_ResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto3_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protov3_header.proto\022\006proto3\"\210\001\n\rReque" +
      "stHeader\022\023\n\013serviceName\030\001 \001(\t\022\022\n\nmethodN" +
      "ame\030\002 \001(\t\022\r\n\005logId\030\003 \001(\t\022*\n\014compressType" +
      "\030\004 \001(\0162\024.proto3.CompressType\022\023\n\013customPa" +
      "ram\030\005 \001(\t\"@\n\016ResponseHeader\022\r\n\005logId\030\001 \001" +
      "(\t\022\017\n\007resCode\030\002 \001(\005\022\016\n\006resMsg\030\003 \001(\t*H\n\014C" +
      "ompressType\022\017\n\013COMPRESS_NO\020\000\022\023\n\017COMPRESS" +
      "_SNAPPY\020\001\022\022\n\016COMPERESS_GZIP\020\002B0\n\037com.wen" +
      "weihu86.rpc.codec.proto3B\rProtoV3Headerb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto3_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto3_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto3_RequestHeader_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "LogId", "CompressType", "CustomParam", });
    internal_static_proto3_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto3_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto3_ResponseHeader_descriptor,
        new java.lang.String[] { "LogId", "ResCode", "ResMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
